// flow-typed signature: c574b136d6c1e21eeb895e312db6198b
// flow-typed version: <<STUB>>/@atomix/eslint-config-react_v^7.1.0/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@atomix/eslint-config-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@atomix/eslint-config-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@atomix/eslint-config-react/example' {
  declare module.exports: any;
}

// Filename aliases
declare module '@atomix/eslint-config-react/example.js' {
  declare module.exports: $Exports<'@atomix/eslint-config-react/example'>;
}
