// flow-typed signature: 916d56f4b34d6e48db0bc8238cb876f6
// flow-typed version: <<STUB>>/shared-types_vgit+https://github.com/mobileFight/shared-types.git/flow_v0.107.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'shared-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'shared-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'shared-types/lib' {
  declare module.exports: any;
}

declare module 'shared-types/prettier.config' {
  declare module.exports: any;
}

declare module 'shared-types/src/equipment' {
  declare module.exports: any;
}

declare module 'shared-types/src' {
  declare module.exports: any;
}

// Filename aliases
declare module 'shared-types/lib/index' {
  declare module.exports: $Exports<'shared-types/lib'>;
}
declare module 'shared-types/lib/index.js' {
  declare module.exports: $Exports<'shared-types/lib'>;
}
declare module 'shared-types/prettier.config.js' {
  declare module.exports: $Exports<'shared-types/prettier.config'>;
}
declare module 'shared-types/src/equipment.js' {
  declare module.exports: $Exports<'shared-types/src/equipment'>;
}
declare module 'shared-types/src/index' {
  declare module.exports: $Exports<'shared-types/src'>;
}
declare module 'shared-types/src/index.js' {
  declare module.exports: $Exports<'shared-types/src'>;
}
